### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by rhagenson** [RHagenson/swsc#2]
Add a basic CI config, something akin to:

```yaml
language: go
sudo: false
go:
    - 1.x
    - master
env: GO111MODULE=on
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod
before_script:
    - go get -t -v ./...
script:
    - go test -v ./...
```

Somehow in the BitBucket->GitHUb transition I removed testing and did not realize I never transferred that. Not difficult to do, but certainly needs to be done sooner rather than later.
